export interface TranslationSet {
  workspaceOverview: string;
  deadlinePlanner: string;
  focusSpace: string;
  calendarTimeline: string;
  changeCompanionQuiz: string;
  darkMode: string;
  activeCompanion: string;
  gmtStatus: string;
  crisisTriageClock: string;
  online: string;
  predictiveRiskEngine: string;
  bareMinimumMode: string;
  enableReminders: string;
  remindersEnabled: string;
  createdBy: string;
  critical: string;
  high: string;
  medium: string;
  low: string;
  securedTaskObjective: string;
  targetSecured: string;
  riskAssessment: string;
  userTypePrediction: string;
  riskCritical: string;
  riskMedium: string;
  riskLow: string;
  recommendation: string;
  recommendationCritical: string;
  recommendationMedium: string;
  recommendationLow: string;
  addNewTarget: string;
  enterTargetTitle: string;
  urgencyLevel: string;
  durationMinutes: string;
  saveTarget: string;
  activeTargetLock: string;
  continueFlowState: string;
  noTasksFound: string;
  completedTasks: string;
  pendingTasks: string;
  completionRate: string;
  pomodorosCompleted: string;
  aiCompanionPraise: string;
  praiseCompanionLabel: string;
  suggestedByCompanion: string;
  googleCalendarLinkDesc: string;
  getAiSurvivalSteps: string;
  triagePriorityLabel: string;
  criticalRescue: string;
  standardAction: string;
  flexibleDepth: string;
  calendarSynced: string;
  syncWithCalendar: string;
  riskLevel: string;
  quickNotes: string;
  notesSubtitle: string;
  addNotePlaceholder: string;
  noteTitlePlaceholder: string;
  saveNote: string;
  aiEnhanceNote: string;
  aiEnhancing: string;
  aiSplitTask: string;
  aiTaskSplitterTitle: string;
  aiTaskSplitterDesc: string;
  aiSplitButton: string;
  splitPlaceholder: string;
  noNotesFound: string;
  noteTopicLabel: string;
}

export const TRANSLATIONS: Record<'en' | 'hi', TranslationSet> = {
  en: {
    workspaceOverview: "Workspace Overview",
    deadlinePlanner: "Deadline Planner",
    focusSpace: "Focus Space",
    calendarTimeline: "Calendar Timeline",
    changeCompanionQuiz: "Change Companion Quiz",
    darkMode: "Dark mode",
    activeCompanion: "Active Companion",
    gmtStatus: "GMT Status",
    crisisTriageClock: "Crisis Triage Clock",
    online: "ONLINE",
    predictiveRiskEngine: "AI Predictive Risk Engine",
    bareMinimumMode: "Bare Minimum Mode",
    enableReminders: "Enable Push Reminders",
    remindersEnabled: "Reminders Enabled",
    createdBy: "Created by niharsevda04@gmail.com",
    critical: "critical",
    high: "high",
    medium: "medium",
    low: "low",
    securedTaskObjective: "SECURED TASK OBJECTIVE",
    targetSecured: "Target Secured!",
    riskAssessment: "Risk Assessment",
    userTypePrediction: "User Mode Prediction",
    riskCritical: "CRITICAL OVERLOAD",
    riskMedium: "MODERATE PRESSURE",
    riskLow: "SECURE & STEADY",
    recommendation: "Advice",
    recommendationCritical: "Danger level critical. Turn on 'Bare Minimum Mode' immediately. Do ONLY the bare minimum to survive today. Postpone all secondary tasks.",
    recommendationMedium: "Steady workload pressure. Stick to your core priorities. Avoid adding any secondary goals today.",
    recommendationLow: "Safe zone. Your timeline looks organized. Keep running Pomodoros to maintain your excellent streak!",
    addNewTarget: "Add New Target Objective",
    enterTargetTitle: "Enter target title or task description...",
    urgencyLevel: "Urgency Level",
    durationMinutes: "Planned Duration (Minutes)",
    saveTarget: "Secure Target",
    activeTargetLock: "Active Focus Target Lock",
    continueFlowState: "Continue Flow State",
    noTasksFound: "No target objectives logged. Add one below to start your triage.",
    completedTasks: "Completed Tasks",
    pendingTasks: "Pending Deadlines",
    completionRate: "Completion Rate",
    pomodorosCompleted: "Pomodoros Done",
    aiCompanionPraise: "Personalized Companion Praise",
    praiseCompanionLabel: "Praise generated by your companion",
    suggestedByCompanion: "Suggested by companion",
    googleCalendarLinkDesc: "Once logged in, you can seamlessly authorize and link Google Calendar deadlines directly inside the Calendar Dashboard.",
    getAiSurvivalSteps: "Generate AI Survival Steps",
    triagePriorityLabel: "Triage Priority",
    criticalRescue: "CRITICAL RESCUE",
    standardAction: "STANDARD ACTION",
    flexibleDepth: "FLEXIBLE DEPTH",
    calendarSynced: "Synced with Google Calendar",
    syncWithCalendar: "Sync with Google Calendar",
    riskLevel: "Risk Level",
    quickNotes: "Quick Scratchpad & Notes",
    notesSubtitle: "Store spontaneous thoughts or task topics. AI can translate and format them instantly.",
    addNotePlaceholder: "Draft your thoughts, list points, or meeting takeaways here...",
    noteTitlePlaceholder: "Note Title (e.g., Marketing Ideas)",
    saveNote: "Save Note",
    aiEnhanceNote: "AI Smart Enhance Note",
    aiEnhancing: "AI is crafting...",
    aiSplitTask: "AI Goal Splitter",
    aiTaskSplitterTitle: "Break Down Complex Goals",
    aiTaskSplitterDesc: "Enter a high-level goal (e.g., 'Deploy app', 'Prepare presentation'). Our AI will split it into a ready-to-execute sub-task array with appropriate priorities.",
    aiSplitButton: "Split into Sub-tasks",
    splitPlaceholder: "e.g., Write research draft on AI ethics",
    noNotesFound: "No notes saved. Write one above to start your visual scratchpad.",
    noteTopicLabel: "Topic or Tag (optional)"
  },
  hi: {
    workspaceOverview: "कार्यक्षेत्र अवलोकन",
    deadlinePlanner: "डेडलॉइन नियोजक",
    focusSpace: "एकाग्रता क्षेत्र",
    calendarTimeline: "कैलेंडर समयरेखा",
    changeCompanionQuiz: "साथी प्रश्नोत्तरी बदलें",
    darkMode: "डार्क मोड",
    activeCompanion: "सक्रिय साथी",
    gmtStatus: "जीएमटी स्थिति",
    crisisTriageClock: "संकट घड़ी",
    online: "ऑनलाइन",
    predictiveRiskEngine: "AI पूर्वानुमानित जोखिम इंजन",
    bareMinimumMode: "न्यूनतम कार्य मोड",
    enableReminders: "पुश रिमाइंडर चालू करें",
    remindersEnabled: "रिमाइंडर सक्रिय हैं",
    createdBy: "niharsevda04@gmail.com द्वारा निर्मित",
    critical: "अति-महत्वपूर्ण",
    high: "उच्च",
    medium: "मध्यम",
    low: "कम",
    securedTaskObjective: "सुरक्षित कार्य उद्देश्य",
    targetSecured: "लक्ष्य सुरक्षित हुआ!",
    riskAssessment: "जोखिम मूल्यांकन",
    userTypePrediction: "उपयोगकर्ता मोड पूर्वानुमान",
    riskCritical: "अत्यधिक काम का दबाव",
    riskMedium: "मध्यम दबाव",
    riskLow: "सुरक्षित और स्थिर",
    recommendation: "सलाह",
    recommendationCritical: "खतरे का स्तर गंभीर है। तुरंत 'न्यूनतम कार्य मोड' चालू करें। आज जीवित रहने के लिए केवल न्यूनतम आवश्यक काम करें। अन्य काम टालें।",
    recommendationMedium: "कार्यभार का सामान्य दबाव है। अपनी मुख्य प्राथमिकताओं पर टिके रहें। आज कोई अतिरिक्त लक्ष्य न जोड़ें।",
    recommendationLow: "सुरक्षित क्षेत्र। आपकी समयसीमा व्यवस्थित दिखती है। अपना बेहतरीन प्रदर्शन बनाए रखने के लिए पोमोडोरो चलाते रहें!",
    addNewTarget: "नया लक्ष्य उद्देश्य जोड़ें",
    enterTargetTitle: "लक्ष्य शीर्षक या कार्य विवरण दर्ज करें...",
    urgencyLevel: "तत्परता स्तर",
    durationMinutes: "योजनाबद्ध अवधि (मिनट)",
    saveTarget: "लक्ष्य सुरक्षित करें",
    activeTargetLock: "सक्रिय ध्यान केंद्रित लक्ष्य",
    continueFlowState: "फ्लो स्टेट जारी रखें",
    noTasksFound: "कोई लक्ष्य दर्ज नहीं किया गया। अपनी संकट ट्रीज शुरू करने के लिए नीचे एक जोड़ें।",
    completedTasks: "पूरे किए गए कार्य",
    pendingTasks: "लंबित समयसीमाएं",
    completionRate: "पूर्णता दर",
    pomodorosCompleted: "पोमोडोरो संपन्न",
    aiCompanionPraise: "व्यक्तिगत साथी प्रशंसा",
    praiseCompanionLabel: "आपके साथी द्वारा उत्पन्न प्रशंसा",
    suggestedByCompanion: "साथी द्वारा सुझाया गया",
    googleCalendarLinkDesc: "एक बार लॉग इन करने के बाद, आप कैलेंडर डैशबोर्ड के भीतर सीधे Google कैलेंडर समयसीमा को जोड़ सकते हैं।",
    getAiSurvivalSteps: "AI जीवन रक्षा योजना बनाएं",
    triagePriorityLabel: "ट्रीज प्राथमिकता",
    criticalRescue: "गंभीर बचाव",
    standardAction: "मानक कार्रवाई",
    flexibleDepth: "लचीला विवरण",
    calendarSynced: "Google कैलेंडर से सिंक किया गया",
    syncWithCalendar: "Google कैलेंडर से सिंक करें",
    riskLevel: "जोखिम स्तर",
    quickNotes: "त्वरित स्क्रैचपैड और नोट्स",
    notesSubtitle: "स्वतःस्फूर्त विचारों या कार्य विषयों को संग्रहीत करें। AI इन्हें तुरंत अनुवाद और प्रारूपित कर सकता है।",
    addNotePlaceholder: "अपने विचार, सूची बिंदु, या बैठक के मुख्य अंश यहाँ लिखें...",
    noteTitlePlaceholder: "नोट का शीर्षक (उदा., मार्केटिंग विचार)",
    saveNote: "नोट सहेजें",
    aiEnhanceNote: "AI स्मार्ट एन्हांस नोट",
    aiEnhancing: "AI तैयार कर रहा है...",
    aiSplitTask: "AI लक्ष्य विभाजक",
    aiTaskSplitterTitle: "जटिल लक्ष्यों को तोड़ें",
    aiTaskSplitterDesc: "एक बड़ा लक्ष्य दर्ज करें (उदा., 'ऐप लॉन्च करें', 'प्रेजेंटेशन तैयार करें')। हमारा AI इसे तुरंत पूरा करने योग्य छोटे कार्यों में विभाजित कर देगा।",
    aiSplitButton: "छोटे कार्यों में विभाजित करें",
    splitPlaceholder: "उदा., AI नैतिकता पर शोध मसौदा लिखें",
    noNotesFound: "कोई नोट सुरक्षित नहीं है। अपने नोट्स शुरू करने के लिए ऊपर लिखें।",
    noteTopicLabel: "विषय या टैग (वैकल्पिक)"
  }
};

export const TRANSLATE_URGENCY: Record<'en' | 'hi', Record<string, string>> = {
  en: {
    critical: "Critical",
    high: "High",
    medium: "Medium",
    low: "Low"
  },
  hi: {
    critical: "अति-महत्वपूर्ण",
    high: "उच्च",
    medium: "मध्यम",
    low: "कम"
  }
};

export const USER_MODE_PREDICTIONS: Record<'en' | 'hi', Record<string, string>> = {
  en: {
    critical: "Procrastination Vulnerable",
    medium: "Slightly Stressed",
    low: "Focused Warrior"
  },
  hi: {
    critical: "टालमटोल की प्रवृत्ति",
    medium: "थोड़ा तनावग्रस्त",
    low: "केंद्रित योद्धा"
  }
};
