export interface TranslationSet {
  workspaceOverview: string;
  deadlinePlanner: string;
  focusSpace: string;
  calendarTimeline: string;
  changeCompanionQuiz: string;
  darkMode: string;
  activeCompanion: string;
  gmtStatus: string;
  crisisTriageClock: string;
  online: string;
  predictiveRiskEngine: string;
  bareMinimumMode: string;
  enableReminders: string;
  remindersEnabled: string;
  createdBy: string;
  critical: string;
  high: string;
  medium: string;
  low: string;
  securedTaskObjective: string;
  targetSecured: string;
  riskAssessment: string;
  userTypePrediction: string;
  riskCritical: string;
  riskMedium: string;
  riskLow: string;
  recommendation: string;
  recommendationCritical: string;
  recommendationMedium: string;
  recommendationLow: string;
  addNewTarget: string;
  enterTargetTitle: string;
  urgencyLevel: string;
  durationMinutes: string;
  saveTarget: string;
  activeTargetLock: string;
  continueFlowState: string;
  noTasksFound: string;
  completedTasks: string;
  pendingTasks: string;
  completionRate: string;
  pomodorosCompleted: string;
  aiCompanionPraise: string;
  praiseCompanionLabel: string;
  suggestedByCompanion: string;
  googleCalendarLinkDesc: string;
  getAiSurvivalSteps: string;
  triagePriorityLabel: string;
  criticalRescue: string;
  standardAction: string;
  flexibleDepth: string;
  calendarSynced: string;
  syncWithCalendar: string;
  riskLevel: string;
  quickNotes: string;
  notesSubtitle: string;
  addNotePlaceholder: string;
  noteTitlePlaceholder: string;
  saveNote: string;
  aiEnhanceNote: string;
  aiEnhancing: string;
  aiSplitTask: string;
  aiTaskSplitterTitle: string;
  aiTaskSplitterDesc: string;
  aiSplitButton: string;
  splitPlaceholder: string;
  noNotesFound: string;
  noteTopicLabel: string;
}

export const TRANSLATIONS: Record<'en' | 'hinglish', TranslationSet> = {
  en: {
    workspaceOverview: "Workspace Overview",
    deadlinePlanner: "Deadline Planner",
    focusSpace: "Focus Space",
    calendarTimeline: "Calendar Timeline",
    changeCompanionQuiz: "Change Companion Quiz",
    darkMode: "Dark mode",
    activeCompanion: "Active Companion",
    gmtStatus: "GMT Status",
    crisisTriageClock: "Crisis Triage Clock",
    online: "ONLINE",
    predictiveRiskEngine: "AI Predictive Risk Engine",
    bareMinimumMode: "Bare Minimum Mode",
    enableReminders: "Enable Push Reminders",
    remindersEnabled: "Reminders Enabled",
    createdBy: "Created by niharsevda04@gmail.com",
    critical: "critical",
    high: "high",
    medium: "medium",
    low: "low",
    securedTaskObjective: "SECURED TASK OBJECTIVE",
    targetSecured: "Target Secured!",
    riskAssessment: "Risk Assessment",
    userTypePrediction: "User Mode Prediction",
    riskCritical: "CRITICAL OVERLOAD",
    riskMedium: "MODERATE PRESSURE",
    riskLow: "SECURE & STEADY",
    recommendation: "Advice",
    recommendationCritical: "Danger level critical. Turn on 'Bare Minimum Mode' immediately. Do ONLY the bare minimum to survive today. Postpone all secondary tasks.",
    recommendationMedium: "Steady workload pressure. Stick to your core priorities. Avoid adding any secondary goals today.",
    recommendationLow: "Safe zone. Your timeline looks organized. Keep running Pomodoros to maintain your excellent streak!",
    addNewTarget: "Add New Target Objective",
    enterTargetTitle: "Enter target title or task description...",
    urgencyLevel: "Urgency Level",
    durationMinutes: "Planned Duration (Minutes)",
    saveTarget: "Secure Target",
    activeTargetLock: "Active Focus Target Lock",
    continueFlowState: "Continue Flow State",
    noTasksFound: "No target objectives logged. Add one below to start your triage.",
    completedTasks: "Completed Tasks",
    pendingTasks: "Pending Deadlines",
    completionRate: "Completion Rate",
    pomodorosCompleted: "Pomodoros Done",
    aiCompanionPraise: "Personalized Companion Praise",
    praiseCompanionLabel: "Praise generated by your companion",
    suggestedByCompanion: "Suggested by companion",
    googleCalendarLinkDesc: "Once logged in, you can seamlessly authorize and link Google Calendar deadlines directly inside the Calendar Dashboard.",
    getAiSurvivalSteps: "Generate AI Survival Steps",
    triagePriorityLabel: "Triage Priority",
    criticalRescue: "CRITICAL RESCUE",
    standardAction: "STANDARD ACTION",
    flexibleDepth: "FLEXIBLE DEPTH",
    calendarSynced: "Synced with Google Calendar",
    syncWithCalendar: "Sync with Google Calendar",
    riskLevel: "Risk Level",
    quickNotes: "Quick Scratchpad & Notes",
    notesSubtitle: "Store spontaneous thoughts or task topics. AI can translate and format them instantly.",
    addNotePlaceholder: "Draft your thoughts, list points, or meeting takeaways here...",
    noteTitlePlaceholder: "Note Title (e.g., Marketing Ideas)",
    saveNote: "Save Note",
    aiEnhanceNote: "AI Smart Enhance Note",
    aiEnhancing: "AI is crafting...",
    aiSplitTask: "AI Goal Splitter",
    aiTaskSplitterTitle: "Break Down Complex Goals",
    aiTaskSplitterDesc: "Enter a high-level goal (e.g., 'Deploy app', 'Prepare presentation'). Our AI will split it into a ready-to-execute sub-task array with appropriate priorities.",
    aiSplitButton: "Split into Sub-tasks",
    splitPlaceholder: "e.g., Write research draft on AI ethics",
    noNotesFound: "No notes saved. Write one above to start your visual scratchpad.",
    noteTopicLabel: "Topic or Tag (optional)"
  },
  hinglish: {
    workspaceOverview: "Workspace Ka Overview",
    deadlinePlanner: "Deadline Planner",
    focusSpace: "Focus Space",
    calendarTimeline: "Calendar Timeline",
    changeCompanionQuiz: "Companion Quiz Badlein",
    darkMode: "Dark Mode",
    activeCompanion: "Active Companion",
    gmtStatus: "GMT Status",
    crisisTriageClock: "Crisis Triage Clock",
    online: "ONLINE",
    predictiveRiskEngine: "AI Predictive Risk Engine",
    bareMinimumMode: "Bare Minimum Mode",
    enableReminders: "Push Reminders Enable Karein",
    remindersEnabled: "Reminders Enabled Hain",
    createdBy: "niharsevda04@gmail.com dwara banaya gaya",
    critical: "critical",
    high: "high",
    medium: "medium",
    low: "low",
    securedTaskObjective: "SECURED TASK OBJECTIVE",
    targetSecured: "Target Secure Ho Gaya!",
    riskAssessment: "Risk Assessment",
    userTypePrediction: "User Mode Prediction",
    riskCritical: "CRITICAL OVERLOAD",
    riskMedium: "MODERATE PRESSURE",
    riskLow: "SECURE & STEADY",
    recommendation: "AI Advice",
    recommendationCritical: "Danger level critical hai! 'Bare Minimum Mode' ko abhi turn on karein. Aaj survive karne ke liye sirf sabse zaroori kaam karein. Baki sab baad me.",
    recommendationMedium: "Workload ka thoda pressure hai. Apni main priorities par focus rakhein aur aaj koi faltu tasks add na karein.",
    recommendationLow: "Aap safe zone me hain! Aapki timeline fully organized lag rahi hai. Streak maintain karne ke liye Pomodoro chalate rahein!",
    addNewTarget: "Naya Target Objective Add Karein",
    enterTargetTitle: "Target ka naam ya task description likhein...",
    urgencyLevel: "Urgency Level",
    durationMinutes: "Planned Duration (Minutes)",
    saveTarget: "Target Secure Karein",
    activeTargetLock: "Active Focus Target Lock",
    continueFlowState: "Flow State Continue Karein",
    noTasksFound: "Koi target objective logged nahi hai. Triage start karne ke liye neeche add karein.",
    completedTasks: "Completed Tasks",
    pendingTasks: "Pending Deadlines",
    completionRate: "Completion Rate",
    pomodorosCompleted: "Pomodoros Done",
    aiCompanionPraise: "Personalized Companion Praise",
    praiseCompanionLabel: "Aapke companion dwara banayi gayi tareef",
    suggestedByCompanion: "Companion ne suggest kiya",
    googleCalendarLinkDesc: "Log in karne ke baad, aap Google Calendar deadlines ko Calendar Dashboard ke andar seamlessly link kar sakte hain.",
    getAiSurvivalSteps: "AI Survival Steps Generate Karein",
    triagePriorityLabel: "Triage Priority",
    criticalRescue: "CRITICAL RESCUE",
    standardAction: "STANDARD ACTION",
    flexibleDepth: "FLEXIBLE DEPTH",
    calendarSynced: "Google Calendar se Synced hai",
    syncWithCalendar: "Google Calendar se Sync karein",
    riskLevel: "Risk Level",
    quickNotes: "Quick Scratchpad aur Notes",
    notesSubtitle: "Apne thoughts ko store karein. AI inko instantly format aur translate kar sakta hai.",
    addNotePlaceholder: "Apne thoughts, list points ya meeting takeaways yahan likhein...",
    noteTitlePlaceholder: "Note Ka Title (e.g., Marketing Ideas)",
    saveNote: "Note Save Karein",
    aiEnhanceNote: "AI Smart Enhance Note",
    aiEnhancing: "AI craft kar raha hai...",
    aiSplitTask: "AI Goal Splitter",
    aiTaskSplitterTitle: "Complex Goals Ko Break Down Karein",
    aiTaskSplitterDesc: "Bada goal enter karein (e.g., 'App deploy karna', 'Presentation prepare karna'). AI use instantly ready-to-execute sub-tasks me split kar dega.",
    aiSplitButton: "Sub-tasks me Split Karein",
    splitPlaceholder: "e.g., AI ethics par research draft likhein",
    noNotesFound: "Koi notes saved nahi hain. Scratchpad start karne ke liye upar likhein.",
    noteTopicLabel: "Topic ya Tag (optional)"
  }
};

export const TRANSLATE_URGENCY: Record<'en' | 'hinglish', Record<string, string>> = {
  en: {
    critical: "Critical",
    high: "High",
    medium: "Medium",
    low: "Low"
  },
  hinglish: {
    critical: "Urgent/Critical",
    high: "High",
    medium: "Medium",
    low: "Low"
  }
};

export const USER_MODE_PREDICTIONS: Record<'en' | 'hinglish', Record<string, string>> = {
  en: {
    critical: "Procrastination Vulnerable",
    medium: "Slightly Stressed",
    low: "Focused Warrior"
  },
  hinglish: {
    critical: "Procrastination Hone Ka Darr",
    medium: "Thoda Stressed",
    low: "Focused Warrior"
  }
};
